### ISSUE TITLE
Docker版本启动报错，建议修改latest标签

### ISSUE THREAD

**Issue by juneix** [awillheartwu/yunplex#1]
群晖安装docker版启动报错，貌似是歌单信息获取有问题，具体见截图。

 TypeError: Cannot read properties of undefined (reading 'playlistName')

![报错截图](https://s2.loli.net/2023/10/06/m5PNFhyi4XVDB7A.jpg)

---

刚研究了一会儿，终于知道原因了，博主你的docker标签有1.0和1.1，但是docker默认下载的是1.0（一路点确认就容易误操作）。建议修改为常见的**latest**标签，获取最新版本，也方便以后自动更新。

另外催更一下下载歌曲目录自定义功能，我下载的基本都是单曲，没有套嵌文件夹的需求，那样反而更麻烦了。

**Comment by awillheartwu** [comment]
好的，个人工作最近较忙，会在这一个月内进行修改

**Comment by awillheartwu** [comment]
1. docker版本号已经修复，目前是latest；
2. 歌曲目录自定义还在摸索，因为当前在查询歌曲的时候需要专辑名和歌手名来用来匹配歌曲，现在这俩信息在本地只能通过本地保存的目录名获取，这样的话就不能进行自定义，不然歌曲识别准确率会下降。这个问题我看看怎么解决
