### ISSUE TITLE
fixbug: 歌单不支持"我喜欢的音乐"

### ISSUE THREAD

**Issue by baozaodetudou** [awillheartwu/yunplex#4]
网易云音乐我喜欢的音乐这个歌单无法进行同步

**Comment by baozaodetudou** [comment]
![image](https://github.com/awillheartwu/yunplex/assets/37683726/bb5cf00d-14b5-4e4c-bb40-4487bc88a0be)
![image](https://github.com/awillheartwu/yunplex/assets/37683726/f512bc64-8090-4ed2-87f5-a4f92d751f23)

**Comment by awillheartwu** [comment]
![企业微信20231201-154638](https://github.com/awillheartwu/yunplex/assets/18117231/d7312b4d-4e40-4cf7-b9b4-ea55f54f2c8c)
我喜欢的音乐在 plex中需要新建一个 "xx喜欢的音乐",这个 xx 是你的网易云用户名
比如你的网易云名字叫:ABC,那你要在 plex 里面新建的歌单名字叫做:ABC喜欢的音乐

我把这一段加入 README 中了,感谢你的提醒
