### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by xushier** [awillheartwu/yunplex#6]
1、希望可以自定义下载音质。如果是会员，最高的超清母带等音质是计算出来的，文件太大。最高hires实际已经够了。
2、会员下载的大多是ncm加密格式，不知道是否调用解密？

**Comment by awillheartwu** [comment]
1.正在重构 2.0 版本,这个建议也正在写
2.我试了超清母带下载下来是 flac格式的

**Comment by xushier** [comment]
哦，那看来是客户端加的密。期待2.0版本！
